Neos:
  Flow:
    persistence:
      doctrine:
        eventListeners:
          -
            events: ['prePersist', 'preUpdate', 'preRemove']
            listener: 'Flownative\Flow\ExtraPrivileges\Security\Authorization\Privilege\Entity\Doctrine\PrivilegeEnforcementListener'
